### ISSUE TITLE
Does not work with ravendb in embedded mode.

### ISSUE THREAD

**Issue by jake1164** [RohithKumbharkar/raven-identity#1]
Embedded mode throws:
Connection string name: 'RavenConnection' could not be parsed, unknown option: 'datadir' 

Using the connection string for embedded from the [documentation](http://ravendb.net/docs/article-page/3.0/Csharp/client-api/setting-up-connection-string).

Which requires the instance to be an EnbeddableDocumentStore.

You should either allow the document store to be initialized by the user, include directions to overload your method or allow for this option.

**Comment by RohithKumbharkar** [comment]
Hey, thank you for taking the time to report the issue.

Although I was aware of that issue, there's more than that I wanted to refactor this entire code base to make it more of a plug-n-play module. But, I got drifted in time & lost the sight of this repository. I'm sure I'll get back to this someday but not in near future till then I guess you could just take the source code & modify it as per the requirement.

**Comment by brandedoutcast** [comment]
Project no longer maintained
